# Generated by Django 4.2.7 on 2025-08-02 10:22

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ppt_file', models.FileField(upload_to='uploads/ppt/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx'])], verbose_name='PPT文件')),
                ('sketch_file', models.FileField(blank=True, null=True, upload_to='outputs/sketch/', verbose_name='Sketch文件')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '转换任务',
                'verbose_name_plural': '转换任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
